version: "3.8"
services:
  backend:
    build: ./backend
    volumes:
      - ./backend:/app
    working_dir: /app
  frontend:
    build:
      context: frontend/
      dockerfile: Dockerfile
    depends_on:
      - backend
    environment:
      - NEXT_TELEMETRY_DISABLED=1
      - NODE_ENV=production
  nginx:
    command: nginx -g "daemon off;"
    depends_on:
      - frontend
    image: nginx
    ports:
      - ${NGINX_PORT:-9000}:80
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
